# Generated by Django 3.0.6 on 2020-07-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_auto_20200721_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='photo_path',
            new_name='photo',
        ),
    ]
